### ISSUE TITLE
Where is the LSUN-room layout dataset?

### ISSUE THREAD

**Issue by ChrisHRZ** [fyu/lsun#23]
I can't find layout dataset in this project. When i export image with data.py. The data only include some .webp image.Where is the layout label? Thank you.

**Comment by fyu** [comment]
Please contact Yinda Zhang (zhangyinda@gmail.com) for questions about room layout dataset.

**Comment by fyu** [comment]
yes...

**Comment by navganti** [comment]
Thank you!
