### ISSUE TITLE
curl http://dl.yf.io/lsun/scenes/classroom_train_lmdb.zip timed out

### ISSUE THREAD

**Issue by ShiboXing** [fyu/lsun#46]
Hello,

in https://github.com/fyu/lsun/blob/7fea09db0dff99b3c58d7e00a884c3e0ffd8018f/download.py#L21, I'm getting a curl timeout issue
```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:12 --:--:--     0



 91 3127M   91 2873M    0     0  2208k      0  0:24:09  0:22:12  0:01:57 2473k
curl: (18) transfer closed with 266626630 bytes remaining to read
```
The partially downloaded classroom zip file has caused a subsequent unzip exception. 
Maybe it can be solved by adding the `-C -` flag? 

Thank you

**Comment by ieee8023** [comment]
An alternative unofficial download option is available here via BitTorrent: https://academictorrents.com/details/c53c374bd6de76da7fe76ed5c9e3c7c6c691c489

**Comment by ShiboXing** [comment]
Hi @fyu, 
 
any chance of getting that PR merged? 

thanks
