### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by rafaelpadilla** [fyu/lsun#52]
The [link ](https://github.com/fyu/lsun/blob/master/download.py#L22) for the dataset is broken.
Many projects  such as pytorch and researchers rely on this source to download LSUN dataset.

**Comment by fyu** [comment]
The link is available now. The downloading server is not very stable these days. The IT department is looking for ways to keep it reliable...

**Comment by rafaelpadilla** [comment]
Hi , Fisher Yu,
Link is back on. :tada: 
Thanks for your time and support. :pray:
